# To use this image with docker-compose please look at the examples in example/docker-compose.
# This file is used for development together with .env which you can create by copying .env.default.
version: '2'
services:
  wiki:
    build: .
    container_name: wiki
    environment:
      MEDIAWIKI_HTTPS: 1
      MEDIAWIKI_SERVER: https://localhost
      MEDIAWIKI_SITENAME: WikiTest
      MEDIAWIKI_LANGUAGE_CODE: it
      #MEDIAWIKI_SECRET_KEY: prova
      MEDIAWIKI_META_NAMESPACE: MyNamespace
      MEDIAWIKI_DB_TYPE: mysql
      #CHANGE IT
      MEDIAWIKI_DB_HOST: $DBMACHINEIP
      MEDIAWIKI_DB_PORT: 3306
      MEDIAWIKI_DB_NAME: wiki
      MEDIAWIKI_DB_USER: wikidb
      #MEDIAWIKI_DB_PREFIX: wiki_
      MEDIAWIKI_DB_TABLE_OPTIONS: ENGINE=InnoDB, DEFAULT CHARSET=binary
      MEDIAWIKI_DB_PASSWORD: wikidb
      MEDIAWIKI_ENABLE_UPLOADS: 1
      MEDIAWIKI_MAX_UPLOAD_SIZE: 10M
      MEDIAWIKI_DEFAULT_SKIN: vector
      #MEDIAWIKI_SMTP: 1
      #MEDIAWIKI_SMTP_SSL_VERIFY_PEER: 0
      #MEDIAWIKI_SMTP_HOST: ${SMTP_HOST}
      #MEDIAWIKI_SMTP_IDHOST: ${SMTP_IDHOST}
      #MEDIAWIKI_SMTP_PORT: 587
      #MEDIAWIKI_SMTP_AUTH: 1
      #MEDIAWIKI_SMTP_USERNAME: ${SMTP_USERNAME}
      #MEDIAWIKI_SMTP_PASSWORD: ${SMTP_PASSWORD}
      #MEDIAWIKI_EMERGENCY_CONTACT: ${EMERGENCY_CONTACT}
      #MEDIAWIKI_PASSWORD_SENDER: ${PASSWORD_SENDER}
      MEDIAWIKI_EXTENSION_VISUAL_EDITOR_ENABLED: 1
      MEDIAWIKI_EXTENSION_USER_MERGE_ENABLED: 1
      MEDIAWIKI_DEBUG: 1
    ports:
    - "80:80"
    - "443:443"
    network_mode: bridge
    volumes:
    - ./volume/mw-images:/images
    - ./testdata/logo.png:/var/www/mediawiki/resources/assets/wiki.png:ro
    - ./testdata/ssl/cert.crt:/etc/ssl/crt/cert.crt:ro
    - ./testdata/ssl/private.key:/etc/ssl/crt/private.key:ro
    - ./testdata/ExtraLocalSettings.php:/var/www/mediawiki/ExtraLocalSettings.php:ro
